name: Docker Image CI

on:
  push:
    branches: ["main", "dev*"]
    tags: ["*.*.*"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        image-tag: [alpine3.16, bullseye-slim, focal, jammy]
    name: ${{ matrix.image-tag }}
    runs-on: ubuntu-latest
    env:
      ASPNET_VERSION: "6.0.9"
      SKIP_DOCKER: "false"
      IS_SEMVER_TAG: "false"
      IS_TAG: "false"
    steps:
      - name: Check Tag Ref
        run: |
          echo "::set-output name=is-tag::${{ startsWith(github.ref, 'refs/tags/') }}"
          echo "::set-output name=reg-tag::${GITHUB_REF#refs/*/}"
          echo "IS_TAG=${{ startsWith(github.ref, 'refs/tags/') }}" >> $GITHUB_ENV
        id: check_tag
      - name: Set version from Tag
        if: ${{ env.IS_TAG == 'true' }}
        run: |
          if [[ '${{ github.ref_name }}' =~ ^([0-9]+\.[0-9]+(\.[0-9]+)?(-.+)?)$ ]]
          then
            echo "IS_SEMVER_TAG=true" >> $GITHUB_ENV
            echo "ASPNET_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "Update ASPNET_VERSION to ${{ github.ref_name }}"
          else
            echo 'No match SemVer *.*.*'; 
          fi
      - name: Skip docker build
        if: ${{ matrix.image-tag == 'focal' && startsWith(env.ASPNET_VERSION, '7.') }}
        run: echo "SKIP_DOCKER=true" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        if: ${{ env.SKIP_DOCKER != 'true' }}
      - name: Docker meta
        id: meta
        if: ${{ env.SKIP_DOCKER != 'true' }}
        uses: docker/metadata-action@v3
        with:
          images: netlah/aspnet-webssh
          tags: |
            type=match,enable=true,priority=900,prefix=,suffix=,pattern=^(\d+\.\d+(\.\d+)?(-.+)?)$,group=1
            type=sha,enable=true,priority=600,prefix=sha-,suffix=,format=short
            type=ref,event=branch,priority=500,prefix=,suffix=
      - name: Login to Docker Hub
        if: ${{ success() && env.SKIP_DOCKER != 'true' && github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        if: ${{ success() && env.SKIP_DOCKER != 'true' && github.event_name != 'pull_request' }}
        env:
          IMAGE_TAG: ${{ env.ASPNET_VERSION }}-${{ matrix.image-tag }}
        shell: pwsh
        run: |
          if (${{ env.IS_SEMVER_TAG }} -eq true) { $repos += @(netlah/aspnet-webssh) }
          $repos += @('${{ secrets.DOCKER_HUB_REPOS }}')
          ./docker-build.ps1 -imageTag ${{ env.IMAGE_TAG }} -dockerRepository $repos -Labels "${{ steps.meta.outputs.labels }}" -Verbose
